spring:
  main:
      web-application-type: reactive
  application:
    name: GATEWAY-SERVICE
    spring:
      main:
        web-application-type=none:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v2/order/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v2/payment/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v2/user/**
#zuul:
#  routers:
#    order-service:
#      path: /api/v2/order/**
#      serviceId: ORDER-SERVICE
#      stripPrefix: true
#    payment-service:
#      path: /api/v2/payment/**
#      serviceId: PAYMENT-SERVICE
#      stripPrefix: true
#    user-service:
#      path: /api/v2/users/**
#      serviceId: USER-SERVICE
#      stripPrefix: true

server:
  port: 2002