spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: PAYMENT-SERVICE

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:2000/eureka/
server:
  port: 2003