spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: ORDER-SERVICE

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/


server:
  port: 2002

management:
  health:
    circuitbreakers:
      enabled: true
    endpoints:
      web:
        exposure:
          include: health
  endpoint:
      health:
        show-details: always


resilience4j:
  circuitbreaker:
    instances:
      orderService:
        registerHealthIndicator: true
        eventConsumerBufferSize:  10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
#        slowCallRateThreshold: 50
#        slowCallDurationThreshold: 10
