spring:
  main:
      web-application-type: reactive
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:2002/
          predicates:
            - Path=/api/v2/order/**
        - id: payment-service
          uri: http://localhost:2003/
          predicates:
            - Path=/api/v2/payment/**

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/
server:
  port: 2001