spring:
  main:
      web-application-type: reactive
  application:
    name: GATEWAY-SERVICE
    spring:
      main:
        web-application-type=none:
  cloud:
    gateway:
      routes:
        - id: supervisor-services
          uri: lb://SUPERVISOR-SERVICE
          predicates:
            - Path=/api/v2/supervisor/**

server:
  port: 2002