spring:
  application:
    name: PERFORMANCES-KPI-SERVICE
  mvc:
    throw-exception-if-no-handler-found: true
  resources.add-mappings: false

server:
  port: 2004

management:
  health:
    circuitbreakers:
      enabled: true
    endpoints:
      web:
        exposure:
          include: health
  endpoint:
      health:
        show-details: always
